### ISSUE TITLE
Move away from strictly ISO 4217 definitions

### ISSUE THREAD

**Issue by maknz** [pocketsmith/exchange#1]
ISO 4217 does not support cryptocurrencies, which are now pervasive in finance and supported by any reputable exchange rates API.

For this reason, we should remove strict reference to the ISO 4217 standard and instead implement a generic definitions file. This would be initially based off the latest ISO 4217 revision, with the addition of popular cryptocurrencies.

**Comment by maknz** [comment]
So we should update the list of currency definitions to include essentially everything that OXR support, and ensuring we're all up to date with the latest definitions, sourcing from ISO 4217 primarily. We can cross-reference with the state of the ISO definitions on our legacy fork to ensure there's nothing missed from what we currently have.

**Comment by davisonja** [comment]
Updated file naming, and content in 0580227e2b18d32347a5c8dd04f73ea42fa3e062 to reflect the inclusion of additional info beyond iso4217.

Now includes currencies that were replaced, along with information about when they were active, and, where available, a reference to their replacement and also some currencies that are not iso4217.

This has maintained equivalency with the legacy fork, but has other additions for some currencies that have left active service.
